name: Deploy Django to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.10"              # adjust if needed
      DJANGO_SETTINGS_MODULE: "emailproject.settings"  # change if your project name differs
      COLLECTSTATIC: "1"                  # set to 0 to skip collectstatic

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Optional: ensure gunicorn is present for production
          python - <<'PY'
          import pkgutil, sys
          missing = [p for p in ("gunicorn",) if not pkgutil.find_loader(p)]
          if missing:
              print("Installing:", missing)
              sys.exit(1)
          PY
        continue-on-error: true

      - name: Ensure gunicorn (if previous step flagged it)
        if: ${{ failure() }}
        run: pip install gunicorn

      # Optional: collect static assets (recommended if you use STATICFILES)
      - name: Collect static files
        if: env.COLLECTSTATIC == '1'
        env:
          # DJANGO settings may need SECRET_KEY and DEBUG for collectstatic if your settings require it
          # For production: set these as App Settings in Azure instead.
          DEBUG: "0"
        run: |
          python manage.py collectstatic --noinput || echo "collectstatic skipped/failed (ensure STATIC_ROOT set)"

      - name: Create deployment package
        run: |
          zip -r release.zip . -x '*.git*' -x '*__pycache__*'

      - name: Upload artifact (for debugging/retention)
        uses: actions/upload-artifact@v4
        with:
          name: django-build
          path: release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "mynewwebapp"   
          slot-name: "production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: release.zip
``
